cache: false
language: node_js
node_js:
  - "6.9.2"

install:
  - npm install

before_script:
  - cp secrets.example.json secrets.json
  - npm install -g grunt-cli

script:
  - grunt test

notifications:
  email:
    on_success: never
    on_failure: change
